# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 20:49
from __future__ import unicode_literals

import json
from django.db import migrations
from django.contrib.auth.hashers import make_password


def insert_tweets(apps, schema_editor):
    Tweet = apps.get_model("twitter", "Tweet")
    User = apps.get_model("twitter", "User")
    User.objects.create(
        username='jack', password=make_password('jack'),
        email='jack@example.com')
    User.objects.create(
        username='ev', password=make_password('ev'), email='ev@example.com')

    # https://discover.twitter.com/first-tweet#jack
    jacks_tweet = {
        'username': 'jack',
        'content': 'just setting up my twttr',
        'created': '2006-03-21T02:50:00'
    }
    # https://discover.twitter.com/first-tweet#ev
    evs_tweet = {
        'username': 'ev',
        'content': 'checking out twttr',
        'created': '2006-03-21T05:51:00'
    }
    Tweet.objects.create(tweet_info_json=json.dumps(jacks_tweet))
    Tweet.objects.create(tweet_info_json=json.dumps(evs_tweet))


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_tweets),
    ]
