# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_initial_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
