# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 16:49
from __future__ import unicode_literals
from datetime import datetime

import json
from django.db import migrations


def convert_tweets(apps, schema_editor):
    Tweet = apps.get_model("twitter", "Tweet")
    User = apps.get_model("twitter", "User")
    
    for tweet in Tweet.objects.all():
        # Deserialize the tweet info
        json_data = json.loads(tweet.tweet_info_json)
        
        # Store the data in our new fields
        tweet.content = json_data['content']
        tweet.created = string_to_datetime(json_data['created'])
        tweet.user = User.objects.get(username=json_data['username'])
        
        # Save!!!
        tweet.save()

def string_to_datetime(dt_string):
    """
    Returns a datetime.datetime object converted from the dt_string parameter.
    """
    return datetime.strptime(dt_string, "%Y-%m-%dT%H:%M:%S")


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20160827_1641'),
    ]

    operations = [
        # migrations.RunPython(create_users),
        migrations.RunPython(convert_tweets),
    ]
