# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 21:04
from __future__ import unicode_literals

import json
from datetime import datetime
from django.db import migrations


def migrate_tweets(apps, schema_editor):
    Tweet = apps.get_model("twitter", "Tweet")
    User = apps.get_model("twitter", "User")

    for tweet in Tweet.objects.all():
        data = json.loads(tweet.tweet_info_json)
        user = User.objects.get(username=data['username'])
        tweet.user = user
        tweet.content = data['content']
        tweet.created = datetime.strptime(
            data['created'], '%Y-%m-%dT%H:%M:%S')
        tweet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20160826_2103'),
    ]

    operations = [
        migrations.RunPython(migrate_tweets),
    ]
