# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20160827_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_info_json',
        ),
    ]
