# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_migrate_tweets_to_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_info_json',
        ),
    ]
