# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_remove_tweet_tweet_info_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created']},
        ),
    ]
